const {escape:e,imageUrl,portableText,query}=require('../lib/blog.cjs');
const {header,footer}=require('../lib/blog-shell.cjs');
const root='https://xinxiang-vibrating-sieve-website-aachanllager.vercel.app';
function shell(title,desc,body,path){return header.replace('__TITLE__',e(title)).replace('__DESCRIPTION__',e(desc)).replace('__CANONICAL__',root+path)+body+footer;}
function date(s){const d=new Date(s);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'});}
module.exports=async function handler(req,res){res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' https://cdn.sanity.io; style-src 'self'; script-src 'self'; base-uri 'none'; frame-ancestors 'self'; form-action 'self'");if(req.method!=='GET'&&req.method!=='HEAD'){res.statusCode=405;res.setHeader('Allow','GET, HEAD');return res.end();}
 const u=new URL(req.url,root);let slug=req.query?.slug||u.searchParams.get('slug');if(!slug&&u.pathname.startsWith('/blog/'))slug=u.pathname.slice(6).replace(/\/$/,'');if(slug&&!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)){res.statusCode=404;return res.end(shell('Article not found','This article is not available.','<section class="section container"><h1>Article not found</h1><a href="/blog">Return to the blog</a></section>','/blog'));}
 try{if(slug){const post=await query(slug);if(!post){res.statusCode=404;return res.end(shell('Article not found','This article is not available.','<section class="section container"><h1>Article not found</h1><p>It may have been unpublished or the address may have changed.</p><a href="/blog">Return to the blog</a></section>','/blog'));}const cover=imageUrl(post.cover?.asset?._ref);return res.end(shell(post.seoTitle||post.title,post.seoDescription||post.excerpt,`<article class="blog-article container"><a class="breadcrumbs" href="/blog">← All articles</a><p class="eyebrow">${e(post.category||'Insights')}</p><h1>${e(post.title)}</h1><p class="blog-meta">${e(post.author||'Xinxiang Vibrating Sieve')} · ${e(date(post.publishedAt))}</p><p class="lead">${e(post.excerpt)}</p>${cover?`<img class="blog-cover" src="${e(cover)}" alt="${e(post.cover?.alt||'')}">`:''}<div class="prose">${portableText(post.body)}</div><div class="reading-note">Have a screening project in mind? <a href="/contact.html">Discuss your application →</a></div></article>`,`/blog/${slug}`));}
 const page=Math.min(10000,Math.max(1,parseInt(u.searchParams.get('page')||'1',10)||1));const data=await query(null,(page-1)*10);const cards=(data.posts||[]).map(post=>{const image=imageUrl(post.cover?.asset?._ref);return `<article class="blog-card">${image?`<a href="/blog/${e(post.slug)}"><img src="${e(image)}" alt="${e(post.cover?.alt||'')}" loading="lazy"></a>`:''}<div><p class="eyebrow">${e(post.category||'Insights')}</p><h2><a href="/blog/${e(post.slug)}">${e(post.title)}</a></h2><p>${e(post.excerpt)}</p><p class="blog-meta">${e(date(post.publishedAt))} · ${e(post.author||'Xinxiang Vibrating Sieve')}</p><a class="text-link dark" href="/blog/${e(post.slug)}">Read article ↗</a></div></article>`}).join('');res.end(shell('Blog | Xinxiang Vibrating Sieve','Screening guides, equipment insights and material handling articles.',`<section class="page-banner"><div class="container"><p class="eyebrow light">KNOWLEDGE & INSIGHTS</p><h1>The screening journal.</h1><p>Ideas, guides and practical perspectives on material handling.</p></div></section><section class="section container"><div class="blog-grid">${cards||'<div class="blog-empty"><h2>No articles yet.</h2><p>New screening guides and equipment articles will appear here.</p><a class="button" href="/resources.html">Explore our selection guides</a></div>'}</div><nav class="pagination" aria-label="Blog pages">${page>1?`<a href="/blog?page=${page-1}">← Previous</a>`:''}${page*10<data.total?`<a href="/blog?page=${page+1}">Next →</a>`:''}</nav></section>`, '/blog'));}
 catch{res.statusCode=503;res.end(shell('Blog temporarily unavailable','Please try again shortly.','<section class="section container"><h1>We could not load the articles.</h1><p>Please try again shortly.</p><a class="button" href="/blog">Try again</a></section>','/blog'));}};

